### ISSUE TITLE
やっぱファイルリスト取得遅い

### ISSUE THREAD

**Issue by yncat** [yncat/falcon#106]
falcon.fileList - DEBUG - File list created in 71.371487 seconds. (2019-12-24 22:20:20,333)
falcon.fileList - DEBUG - 259 directories and 1040 files found. (2019-12-24 22:20:20,333)
リスト表示は1秒かかってない
けしからん！！！！！
なんとかしてえなあ

**Comment by yamahubuki** [comment]
こっちのSSDでは1300ファイルのディレクトリでも

1.756297 seconds. (2020-01-05 16:20:29,621)
1.635183 seconds. (2020-01-05 16:21:28,638)
1.686189 seconds. (2020-01-05 16:21:35,744)
1.424743 seconds. (2020-01-05 16:21:39,671)
1.219373 seconds. (2020-01-05 16:21:42,991)

なので、実験にもならなそう。

HDDでやると
0.959706 seconds. (2020-01-05 16:24:16,714)
0.956223 seconds. (2020-01-05 16:24:21,165)
0.732279 seconds. (2020-01-05 16:24:24,564)
0.508200 seconds. (2020-01-05 16:24:27,639)
0.514796 seconds. (2020-01-05 16:24:30,603)

となるので、これはキャッシュなどの影響と考えられてやっぱり試せない。
てかSSDより早いってどゆことよ。CドライブのSSD、そんなに他プロセスがreadしてんのかしら。

**Comment by yncat** [comment]
うちのHDDが異常に遅いのかもしれない。でも、１３００ファイルだったら、少なくとも0.5s以内には操作可能にしたい。

**Comment by yncat** [comment]
#37 でやろう
