### ISSUE TITLE
右クリックメニューを作る

### ISSUE THREAD

**Issue by yamahubuki** [yncat/falcon#13]

**Comment by yncat** [comment]
http://www.asahi-net.or.jp/~gv4j-sgur/narik/stp002b.htm

**Comment by yncat** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmenuiteminfoa

**Comment by yncat** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmenuitemcount

**Comment by yncat** [comment]
だいたい作ったけど、送るメニューは独自実装した方が良さそう。(queryContextMenuの中身をそのままTrackPopupMenuで出せば問題ないんだけれど、独自で描画してるので、そのへんがうまくいかない)

**Comment by yncat** [comment]
iContextMenuについてめっちゃ詳しく書いてある。
https://devblogs.microsoft.com/oldnewthing/20040920-00/?p=37823

**Comment by yncat** [comment]
これは、もの自体はできたので閉じます
