### ISSUE TITLE
削除・ゴミ箱においてはどれが失敗したか取得できるようにする

### ISSUE THREAD

**Issue by yamahubuki** [yncat/falcon#142]
#135 で必要

**Comment by yncat** [comment]
どれが失敗したかを取るメソッドは整ってないと思うけど、ゴミ箱は項目ごとに処理刷るようになった。

**Comment by yncat** [comment]
どれが失敗したかを採る方法を、 trash メソッドの中に書いた

**Comment by yncat** [comment]
ゴミ箱は大丈夫そうだけど、削除がcommonFailureを通っていないので、なおしときます

**Comment by yncat** [comment]
#175 で直した
