### ISSUE TITLE
タブコントロールをよみあげない

### ISSUE THREAD

**Issue by yamahubuki** [yncat/falcon#149]
wx.Accessibleの導入を検証
https://wxpython.org/Phoenix/docs/html/wx.Accessible.html

**Comment by yncat** [comment]
こないだもいったけど、ctrl+tabで切り替わるのだから、今の動作で特に問題を感じないのだけど…

**Comment by yamahubuki** [comment]
タブが増えた時に、「検索結果」とか「進捗状況」とか「メイン」とか案内欲しくない？

いらないならいいけど。

**Comment by yamahubuki** [comment]
#236 のせいでそう感じているだけで、メニューバー削除とかすればきちんと読み上げられることを確認した。

こちらはクローズし、 #236 の解決を目指す。
