### ISSUE TITLE
いろんなところの例外処理をいい感じにする

### ISSUE THREAD

**Issue by yamahubuki** [yncat/falcon#167]
とりあえずmisc.calcHashだけど、他でもつかえそうないい感じのやつほしい。
exceptしたら何のエラーでもとりあえずぶん投げる先があって、そこがユーザへの通知とログ出力してくれるてきな。

**Comment by yncat** [comment]
とりあえず #267 で様子をうかがう

**Comment by yncat** [comment]
これはとりあえずいいでしょう。
