### ISSUE TITLE
読み上げ機能をメニューから実行すると、リストビューにフォーカスが戻った読み上げによって上書きされてしまう

### ISSUE THREAD

**Issue by yncat** [yncat/falcon#194]
メニューから実行したときは、ちょっと関数実行を遅延させないとだめそうだけど、コマンド実行と区別できるかな……。あるいは、もっといい方法。

**Comment by yncat** [comment]
#197 でやったけど、いまNVDAしかない。 pc-talkerでやってみてコメントいただけると @yamahubuki

**Comment by yamahubuki** [comment]
この変更をpullせずに試しましたが、問題なく音声は聞こえています。
PC-Talkerについては対策不要と思われます。

一方で、対策導入後に特に問題も起きていないので、NVDA利用者向けにやるのは問題なさそうです。

**Comment by yncat** [comment]
AZMS
