### ISSUE TITLE
CD/DVD/BDドライブのタイプが全て「CD-ROMドライブ」になっているのをどうにかする

### ISSUE THREAD

**Issue by yamahubuki** [yncat/falcon#23]

**Comment by yncat** [comment]
実装方法分からないので聞いてみた。
https://ja.stackoverflow.com/questions/59872/光学ドライブの正確なタイプを取得する方法

**Comment by yncat** [comment]
聞いてみたら、動きそうな実装貼ってくれた人がいたので、火曜日にそれやってみる。C++でできるはず。

**Comment by yncat** [comment]
とりあえず、C#のサンプルをC++に移植した。
https://docs.microsoft.com/en-us/windows/win32/api/imapi2/ne-imapi2-imapi_feature_page_type
ここに feature の対応表があるので、これを使って区別する基準を考える。

**Comment by yncat** [comment]
でけた。 #43
