### ISSUE TITLE
拡張子の独自関連付け

### ISSUE THREAD

**Issue by yamahubuki** [yncat/falcon#231]
<dir>、<default>、あとは拡張子ごとでいいと思う
任意のアプリケーションのフルパスと対応付ける。%1を選択中項目名で置き換える

**Comment by yncat** [comment]
よくわからない。新しいタブで開く、ではないの？

**Comment by yamahubuki** [comment]
MyEditとかやりたいやつ

**Comment by yncat** [comment]
それは、「指定アプリを開く」がすでにあるんじゃないの？

**Comment by yamahubuki** [comment]
「ここで開く」は、現在開いているウィンドウと同じ場所を起点にアプリを開くためのもの。
つまり、ファイルに対して何かをすることはできない。当然、拡張子によって何かを変えるとかもない

**Comment by yamahubuki** [comment]
厳密に言うと、拡張子の独自関連付けはただEnter押したときの処理だからまた別の機能になります。

**Comment by yncat** [comment]
myfileのあの機能はうざいだけなので、独自関連付けで実行をなにかのキーでできるようにするって感じかな。
ctrl+returnは使われてるので。

**Comment by yncat** [comment]
間違えたw
