### ISSUE TITLE
タブコントロールで左右矢印キーを押したらなぜかリストボックス内が反応している

### ISSUE THREAD

**Issue by yamahubuki** [yncat/falcon#236]

**Comment by yamahubuki** [comment]
原因は２つ。
１つ目は、タブ切り替え後にlistctrlをアクティベートしていて、それがキーを放すより先だとリスト側にキー入力が行くこと。

もう一つは、メニューバー上に表示したショートカットが動作してしまうこと。
こちらは対策を考えねばならないが、キー入力なのかメニューバーから操作したのかを判別する必要がある。

**Comment by yncat** [comment]
可能性のある解決策としては、
- keymapモジュールでなにかして、実行されたメニューコマンドのショートカットキーを調べて、キーコードのリストをもらう。
- そのキーコードを wx.GetKeyboardState で調べて、全部押されていたらショートカットキー。そうでなければ、メニューバー。
