### ISSUE TITLE
音声出力先を指定できるようにする

### ISSUE THREAD

**Issue by yncat** [yncat/falcon#26]
今だと、NVDAとPCTKを両方起動していると、強制的にNVDAにしかいかなくてうざい。

**Comment by yncat** [comment]
これ、結局できたんだっけ。 @yamahubuki

**Comment by yamahubuki** [comment]
SAPI4だけうまく動かなくてコメントアウトになっているので対処してください。

**Comment by yncat** [comment]
sapi4いるかな？個人的には5あれば十分だと思うのだけど。というか、動作確認がちょっと大変。

**Comment by yncat** [comment]
試しにNVDAでsapi4貯めそうとしたら、うちのsapi4がぶっ壊れててぜんぜん動かせなかった。

**Comment by yamahubuki** [comment]
今度テストマシンかしましょう。
Taroちゃんがいますよ

**Comment by yncat** [comment]
モジュール読み込めないバグは治ったけれど、AO2のバグかなんかでsapi4動かなかった。当面、sapi4のサポートはドロップして運用します。
ひとまず、それ以外の音声は出るので、閉じます。
