### ISSUE TITLE
検索キーワードの履歴機能をつける

### ISSUE THREAD

**Issue by yamahubuki** [yncat/falcon#344]

**Comment by yamahubuki** [comment]
@yncat 
履歴機能できたけど、通常検索とファイル内容選択を切り替えた時、履歴を基に選択肢を切り替えると、入力内容がクリアされてしまう。
文字だけなら無理やり保存しといて書き戻す手段もあるけど、カーソル位置とか洗濯状況とか言われたらもう知らない。
さて、どういうインタフェースがいいと思いますか？

**Comment by yncat** [comment]
そんなに長い入力をそこですることはないし、履歴にあるなら矢印キーで選び直せば良いので、消えちゃっても問題ないと思います！

**Comment by yamahubuki** [comment]
履歴にないものを入力するとき、
入力→TABキー→ラジオボタンに移動するのでファイル内容検索に切り替え→内容が消える
ということになるので、正規表現使うときとかは気を付けないとですねえ。

とりあえずはこのままにしておきます。
