### ISSUE TITLE
ネットワークリソース一覧の取得をworkerThreadTasksから切り出す

### ISSUE THREAD

**Issue by yamahubuki** [yncat/falcon#350]
miscあたりに切り出して、現在の非同期と合わせて同期処理でも取得可能にしてください。
#143 に使います。
FileListTab.GetRootObject()から、指定の名前のネットワークリソースを取得する必要があります。

**Comment by yncat** [comment]
切り出せなかったけど、同期処理で実行できるようにはしました。
