### ISSUE TITLE
ドライブルートにおいてのみ、ディレクトリ作成ができない

### ISSUE THREAD

**Issue by yamahubuki** [yncat/falcon#359]
logを読むと、C:\0となるべきところがC:0となっているようだ。

**Comment by yamahubuki** [comment]
この件、どうやらos.path.joinはC:のように\を含まない状態でのルートパスと何かを結合しようとすると挙動がおかしいようだ。

他の箇所でも影響出る可能性あるので、全部文字列連結に置き換えないと危なそう

**Comment by yncat** [comment]
あー、これ、貼り付けのいろいろやってるときに引っかかったわ。これはos.pathのバグです。
