### ISSUE TITLE
DVD-RW ドライブが DVD+R DL ドライブってことになっちゃう

### ISSUE THREAD

**Issue by yncat** [yncat/falcon#44]

**Comment by yamahubuki** [comment]
docsフォルダ内の分類方法のドキュメントを見直しました。
dllにあれを反映してください。

**Comment by yncat** [comment]
@yamahubuki が直してくれたので、あとでdllコンパイルする。

**Comment by yncat** [comment]
#73 やったら試す

**Comment by yncat** [comment]
#75 でdllを最新にしたので、どうかな

**Comment by yamahubuki** [comment]
少なくとも手元のドライブについては正しく表示されるようなので、これでクローズします。
