### ISSUE TITLE
ファイルやフォルダの属性、タイムスタンプ変更機能を作る

### ISSUE THREAD

**Issue by yncat** [yncat/falcon#8]
1画面でやりたい by @yamahubuki

**Comment by yamahubuki** [comment]
機能自体はコーディング済み。UI実装待ち。#27が終わり次第取り組む

**Comment by yncat** [comment]
属性はできてると思うけど、タイムスタンプがまだかな？

**Comment by yncat** [comment]
#27 終わってるよ

**Comment by yncat** [comment]
タイムスタンプは、GUI側は当面対応しないことにしたので、これは閉じます。日時変更に対応する場合は、別のissueを立てるようにしてください。
